// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(connection) {
    var schema;
    schema = new connection.base.Schema({
      hostHost: {
        type: String,
        required: true,
        index: true
      },
      count: {
        type: Number
      }
    });
    return module.exports != null ? module.exports : module.exports = connection.model("ShortHostItem", schema);
  };

}).call(this);
